version: '3.8'

services:
  # 1. PostgreSQL Veritabanı Servisi
  postgres-db:
    image: postgres:16-alpine
    container_name: digital-wallet-db
    environment:
      POSTGRES_DB: digitalwallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Spring Boot Backend Servisi
  backend-app:
    build: .
    container_name: digital-wallet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/digitalwallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db

volumes:
  postgres_data: